travis:
  secure:
    BINSTAR_TOKEN: QmYI1MUXq25fJKfJhmjrFLga4q0G+o1DG1TrAQZ1Dz7OR3ammLaIiN4ywmIBvQYaVqE0Ol8DWK1GCFKFzHVBotslC6+efHtV2dD6xNbYIZTW878Ee5+zCkmKvMre5ainKHCVI9qce5JVQrHXD6JppMHQhRhDnkA7fQRwGjYnHteLCfGFT0uXgUxexl9kR3FlXkAF8LA8Owh+J4h6ztnD+l3DKtsc8rj2sYWmJSvu77mCBaek+jMrj9dEX/4KHGkD69t3CC8qFY3GP6oIIzv+M0Er+tKYdy8r39wiwoNdaT7YjwBor9jvr9ZqsDt9eCL4B3twhpgtpagek/FxT0YNg+AhnfD6L+GenG8dYxHhpyAkRRZIyA60DyRnqoQ+w9RafHqIaJcbs4Fk3cDUQBXxycb0hdCt67dXQ5z1blNUCMx985PMIg1y0t9zwQCQgUk8dzEk6kTXbjBvb7oKySXRXVU4hkgxtc/ce46rZO2kPtZ9Gv1RfUHM5mbomWYauXbGMxlGcu2t15Jg3/2mB1EakU6z+noywRzRE8PXEB6eYjg54oZIr7VK5QdTT3/+8sKq4351WytA2LJrcbo60aGqJoTaY41kfwMgol/RUoyoUxF3uvAX84PZsWw2CsMzNSz3JauBKlNcmKOHfx4uBYhDc32nrR2IC8UI1dXUYYM2Q6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
