travis:
  secure:
    BINSTAR_TOKEN: NJJzSfr3cxGz3YAlTQDSUreUlS8/u0/+/YyGbPXTCoTIVgLXMCKOKN8jFBLHRS/gGD8Jur7NK6XXpKMrm6UhPQ1pQbYe41uKlc8UwdslnpUGPZLA+nXe5sZBsT+6OBTy4K2Ogh+3gZVOy0jmnoalrUezA74v984iMwmjpyijPhZC46Qh6qIsqgVDEOvdDQ0pnoVZG0IS7ZBiU8IEtkFWfpr7tDrAbLQ4ZkqvgSiWKz/zScA9+9oixe5iBT4czPwhM2s0Ap49GlATmX8tj7IjdS82X/V/7UQPQWKR4fk3ZisP4N0z8Olp7KWW+w4M6UBWqy+Ms0tD/k8FBSBM70A3blnfnVnc7mTM3mMYHyTrcDYrVsX/s85Bq1sDiFFltPGA3B9KhuYZ6ZguwWC5Ue+rDgtXDFLuczfkyJA1BzhcTj/0a+DvutkARmk8kftFBGy5ie+NsWkUHGnkvlflJeECmB5t/0ms+zV4bVofmfJTOvkHSS3ummVQ+e7sp8ybCoZpNxoJpw3dITtNeeUKT8CxvVp+w4o6K/7VSII+VOJSYKvoVLDUXrEfbUsj53XvOVXgtIFeR7dezrOj6LNU7C/q5N9Z12Bymp+0gw56AFGyW0IozZe0zBcKyf8FDU1mnyoIn7fDvnltvXBDjzDD9UoyuUM6MyDws1p8LI4GhXLS3/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
